controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  buff_controller:
    type: rm_buff/BuffController
    joint: "rotating_joint"
    usefeedforward: true
    usedynamic: true
    pid: { p: 0.6, i: 0.05, d: 0.0, i_max: 0.03, i_min: -0.03, antiwindup: true, publish_state: true }
    feedforward:
      kf: 0.1
